spring:
  profiles:
    group:
      default:
        - ${reservation-api.modules.common}
        - ${reservation-api.modules.application}
        - ${reservation-api.modules.persistence}
        - ${reservation-api.modules.web}
      dev:
        - default
        - ${reservation-api.modules.persistence}-${reservation-api.profiles.dev} # override the properties
        - ${reservation-api.modules.web}-${reservation-api.profiles.dev}

reservation-api:
  profiles:
    dev: dev
  #    prod: prod
  modules:
    web: web
    persistence: persistence
    application: domain
    common: utils
  security:
    jwt:
      secret: secret123456
      prefix-header: Bearer
      access-token:
        expiry: 10
        header: Access-Token
      refresh-token:
        expiry: 30
        header: Refresh-Token
      authorities-claim: authorities
    login:
      url: /api/login
      username-parameter: login
      password-parameter: password
    authorization-error-header: Authorization-Error

